import sys
sys.path.append("../..")
import BasicCalculator

BasicCalculator.BasicCalculatorParser("1")
BasicCalculator.BasicCalculatorParser("-1")
BasicCalculator.BasicCalculatorParser("1 + 2")
BasicCalculator.BasicCalculatorParser("1 - 2")
BasicCalculator.BasicCalculatorParser("1 + -2")
BasicCalculator.BasicCalculatorParser("1 - -2")
BasicCalculator.BasicCalculatorParser("-1 + -2")
BasicCalculator.BasicCalculatorParser("-1 - -2")
BasicCalculator.BasicCalculatorParser("1 + 2 - 3")
BasicCalculator.BasicCalculatorParser("1 + -2 - 3")
BasicCalculator.BasicCalculatorParser("1 + 2 - -3")
BasicCalculator.BasicCalculatorParser("1 + -2 - -3")
BasicCalculator.BasicCalculatorParser("1 * 2")
BasicCalculator.BasicCalculatorParser("-1 * 2")
BasicCalculator.BasicCalculatorParser("1 * -2")
BasicCalculator.BasicCalculatorParser("-1 * -2")
BasicCalculator.BasicCalculatorParser("1 / 2")
BasicCalculator.BasicCalculatorParser("-1 / 2")
BasicCalculator.BasicCalculatorParser("1 / -2")
BasicCalculator.BasicCalculatorParser("-1 / -2")
#BasicCalculator.BasicCalculatorParser("1 / 0") # divide by zero
BasicCalculator.BasicCalculatorParser("1 % 2")
BasicCalculator.BasicCalculatorParser("-1 % 2")
BasicCalculator.BasicCalculatorParser("1 % -2")
BasicCalculator.BasicCalculatorParser("-1 % -2")
BasicCalculator.BasicCalculatorParser("2 ^ 3")
BasicCalculator.BasicCalculatorParser("-2 ^ 3")
BasicCalculator.BasicCalculatorParser("2 ^ -3")
BasicCalculator.BasicCalculatorParser("-2 ^ -3")
BasicCalculator.BasicCalculatorParser("2 ^ 3 ^ 4")
BasicCalculator.BasicCalculatorParser("(2 ^ 3) ^ 4")
BasicCalculator.BasicCalculatorParser("3 ^ 2 - 3 * (-2 + 4) / 6 + 5")