import sys, time
sys.path.append("../..")
import jsonpeg as json

print(json.jsonParser("3").load())
print(json.jsonParser("-3").load())
print(json.jsonParser("0").load())
print(json.jsonParser("null").load())
print(json.jsonParser("true").load())
print(json.jsonParser("false").load())
print(json.jsonParser("\"fast\"").load())
print(json.jsonParser("3.1").load())
print(json.jsonParser("-3.1").load())
print(json.jsonParser("3.1e4").load())
print(json.jsonParser("3.1e-4").load())
print(json.jsonParser("[true, false, true, true]").load())
print(json.jsonParser("[-1, 0, 1, 2]").load())
print(json.jsonParser("[-1.2, 0.1, 1.2, 2.3]").load())
print(json.jsonParser("[true, -1, 2.3, \"fast\"]").load())
print(json.jsonParser("[true, -1, {\"fast\" : 2.3}]").load())
print(json.jsonParser("[]").load())
print(json.jsonParser("{}").load())
print(json.jsonParser("{\"key\": \"value\"}").load())
print(json.jsonParser("{\"key\": \"\"}").load())
print(json.jsonParser("{\"key\": true}").load())
print(json.jsonParser("{\"key\": false}").load())
print(json.jsonParser("{\"key\": null}").load())
print(json.jsonParser("{\"key\": 1}").load())
print(json.jsonParser("{\"key\": -1.2}").load())
print(json.jsonParser("{\"key\": [1, -1.2]}").load())
#print(json.jsonParser("{\"key\": {1, -1.2}}").load()) # this fails correctly
print(json.jsonParser("{\"key\": {\"value\": -1.2}}").load())
print(json.jsonParser("{\"key\": {\"value\": -1.2}}{\"key2\": {\"value2\": -2.4}}").load())