import sys
sys.path.append("../..")
import jsonpeg as json

json.jsonpegParser("3")
json.jsonpegParser("-3")
json.jsonpegParser("0")
json.jsonpegParser("null")
json.jsonpegParser("true")
json.jsonpegParser("false")
json.jsonpegParser("\"fast\"")
json.jsonpegParser("3.1")
json.jsonpegParser("-3.1")
json.jsonpegParser("3.1e4")
json.jsonpegParser("3.1e-4")
json.jsonpegParser("[true, false, true, true]")
json.jsonpegParser("[-1, 0, 1, 2]")
json.jsonpegParser("[-1.2, 0.1, 1.2, 2.3]")
json.jsonpegParser("[true, -1, 2.3, \"fast\"]")
json.jsonpegParser("[true, -1, {\"fast\" : 2.3}]")
json.jsonpegParser("[]")
json.jsonpegParser("{}")
json.jsonpegParser("{\"key\": \"value\"}")
json.jsonpegParser("{\"key\": true}")
json.jsonpegParser("{\"key\": false}")
json.jsonpegParser("{\"key\": null}")
json.jsonpegParser("{\"key\": 1}")
json.jsonpegParser("{\"key\": -1.2}")
json.jsonpegParser("{\"key\": [1, -1.2]}")
json.jsonpegParser("{\"key\": {1, -1.2}}") # this fails correctly
json.jsonpegParser("{\"key\": {\"value\": -1.2}}")
json.jsonpegParser("{\"key\": {\"value\": -1.2}}{\"key2\": {\"value2\": -2.4}}")